version: "3.0"
networks:
  frontend:
  backend:
services:
  # Chart service
  dojo_charts_service:
    image: dojo_chart:latest
    build:
      dockerfile: Dockerfile
      context: ./charts/
    container_name: charts
    env_file:
      - microservices.env
    environment:
      PORT: 8100
    ports:
      - "8101:8100"
  # Images service
  dojo_images_service:
    image: dojo_images:latest
    build:
      dockerfile: Dockerfile
      context: ./images/
    env_file:
      - microservices.env
    container_name: images
    environment:
      PORT: 8100
    ports:
      - "8102:8100"
  # Search service
  dojo_search_service:
    image: dojo_search:latest
    build:
      dockerfile: Dockerfile
      context: ./search/
    container_name: search
    env_file:
      - microservices.env
    environment:
      PORT: 8100
    ports:
      - "8103:8100"
  #Management Service#
  dojo_web_service:
    image: dojo_web:latest
    build:
      dockerfile: Dockerfile
      context: ./web/
    container_name: web
    depends_on:
      - dojo_charts_service
      - dojo_images_service
      - dojo_search_service
    environment:
      PORT: 3000
      API_VERSION: v1
    ports:
      - "3000:3000"
